"""add impact_score / event_type / impact_factors to events"""

revision = 'c077e7dba698'
down_revision = '646e4efcc20b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('impact_score', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('event_type', sa.String(length=20), nullable=True))
    op.add_column('events', sa.Column('impact_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_impact_score'), 'events', ['impact_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_impact_score'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_column('events', 'impact_factors')
    op.drop_column('events', 'event_type')
    op.drop_column('events', 'impact_score')
    # ### end Alembic commands ###
